docs/guides/index.rst
docs/guides/sources.rst

doc(sources): show how to configure sources fields

---

depc/sources/warp/interval.py
depc/sources/warp/threshold.py

feat(warp10): return the stack in case of unparsable response

---

depc/apiv1/qos.py
ui/app/scripts/app.js
ui/app/scripts/controllers/team/permissions.js
ui/app/views/team/permissions.html

feat(permissions): do not fetch all users during the first display
fix(api): only users of a team can display its QoS

Do not fetch all users during the first display

---

depc/apiv1/dependencies.py
depc/controllers/dependencies.py
depc/utils/neo4j.py
scheduler/dags/__init__.py
scheduler/dags/operators/__init__.py
scheduler/dags/operators/rule_operator.py
scheduler/dags/save_config.py
tests/apiv1/test_dependencies.py
tests/conftest.py
tests/controllers/test_dependencies.py
ui/app/index.html
ui/app/scripts/controllers/modal_relationship_periods.js
ui/app/scripts/controllers/team/dependencies.js
ui/app/scripts/controllers/team/item.js
ui/app/scripts/services/config.js
ui/app/scripts/services/dependencies.js
ui/app/scripts/services/modal.js
ui/app/styles/main.css
ui/app/views/modals/relationship_periods.html
ui/app/views/team/dependencies.html
ui/app/views/team/item.html

This PR allows users to filter the dependencies for a particular day, including or not the inactive nodes.

Hide old dependencies

---

ui/package-lock.json
ui/package.json

bump(ui): upgrade dependencies

---

depc/apiv1/dependencies.py
depc/controllers/dependencies.py
tests/apiv1/test_dependencies.py
ui/app/scripts/controllers/team/dependencies.js
ui/app/scripts/services/dependencies.js
ui/app/views/team/dependencies.html

fix(ui,api): rename the term 'old' in 'inactive'

---

docs/quickstart/configuration.rst
docs/quickstart/index.rst
docs/quickstart/qos.rst

doc(quickstart): move the creation of rule before the configuration

---

depc/context.py
tests/apiv1/test_dependencies.py
tests/conftest.py

tests(neo4j): skip some tests if neo4j instance is unavailable

---

.github/CODEOWNERS

chore(github): add default reviewers

---

consumer/main.py
docker-entrypoint.sh

* Ability to deploy the consumer in a container-based environement.
* Fix the `consumer/main.py`, for the `make consumer` command

Add the Kafka consumer to docker-entrypoint.sh

---

ui/app/scripts/controllers/team/rules.js

fix(ui): remove unwanted debug line

---

ui/app/scripts/controllers/team/rules.js

fix(ui): bad state in rule's panel result

---

ui/Dockerfile
ui/Gruntfile.js
ui/package-lock.json
ui/package.json

Upgrade the `grunt-contrib-connect` package to the last release: **v2.0.0**.
The `Gruntfile.js` changes come from [stackoverflow.com/a/33113395](https://stackoverflow.com/a/33113395).

upgrade grunt-contrib-connect and change to debian strech for the docker image

---

depc/admin.py

feat(admin): customize the admin views

---

depc/models/users.py
pytest.ini
requirements.txt

bump(api,airflow): upgrade dependencies

---

depc/apiv1/dependencies.py
depc/controllers/dependencies.py
tests/apiv1/test_dependencies.py
tests/controllers/test_dependencies.py
ui/app/scripts/controllers/team/dependencies.js
ui/app/scripts/services/dependencies.js
ui/app/views/team/dependencies.html

feat(api,ui): display downstream dependencies

---

ui/app/scripts/controllers/teams.js
ui/app/styles/main.css
ui/app/views/teams.html

feat(ui): display managers of teams in homepage

---

ui/app/scripts/services/modal.js

fix(ui): prevent config popup to be closed by error

---

docs/api/index.rst
docs/api/news.rst

fix(doc): add news section and remove results

---

depc/apiv1/dependencies.py
depc/controllers/dependencies.py
tests/apiv1/test_dependencies.py
ui/app/scripts/controllers/team/dependencies.js
ui/app/scripts/controllers/team/label.js
ui/app/scripts/services/dependencies.js
ui/app/views/team/dependencies.html
ui/app/views/team/label.html

feat(api): search node before using the pattern method

---

docs/installation.rst

Into the preamble sub-section:
- Fix link to download the Neo4j database ;
- Add OVH Beamium into the third party requierements.

Add missing required third party and fix download link

---

docs/guides/difference-qos-sla.rst
docs/guides/index.rst
docs/index.rst
docs/installation.rst

doc(index,sla): change the homepage and add a guide about SLA

---

README.rst

doc(readme): add a more precise description of DepC in the readme file

---

.travis.yml
depc/context.py

feat(ci): use travis to launch tests

---

ui/app/views/team/checks.html
ui/app/views/team/rules.html

- Change `Associate checks` to `Associate indicators` ;
- Change the button label to launch a rule.

Change some button labels

---

AUTHORS
CONTRIBUTORS

fix(authors): change authors and contributors

---

scheduler/dags/operators/__init__.py

fix(scheduler): dependencies with the same name was merged

---

ui/app/styles/main.css

Signed-off-by: Maxime Caruchet <maxime.caruchet@corp.ovh.com>

fix(ui): change QoS font size to fix blocks alignment

---

ui/app/views/team/item.html

fix(ui): display dependencies for nodes without qos

---

scheduler/dags/operators/__init__.py

In some cases Beamium creates corrupted file into the sinks directory because the multiple metrics are not completely written into the source file.
This fix aims to create a temporary file first (`xxxxyyyyzzzz.metrics.tmp`) and then rename it (`xxxxyyyyzzzz.metrics`) in order to be ingested by Beamium.

fix(scheduler): create a temporary Beamium file for multiple metrics

---

docs/guides/queries.rst

doc(queries): explain how to skip a node from label average

---

.travis.yml
depc/utils/qos.py
docs/installation.rst
requirements.txt
tests/utils/test_qos.py

**About Travis CI:**
- Drop old `Trusty` Ubuntu OS to use `Bionic`.
- Drop Python 3.5 interpreter.
- Add Python 3.7 interpreter.
- Add Python Black check.
**About the code:**
- Move some logic from `compute_qos_from_bools` to `_compute_qos` to make it easier to test.
- Add some test cases.
**About the requirements:**
- Bump from `numpy==1.12.1` to `numpy==1.19.1`
**About the documentation:**
- Update Python requirement in doc

Bump NumPy, add test cases, update CI
