depc/utils/warp10.py
From Warp10 Docs:
```
The table of values can have two to five columns:
[ 0 3.14 ]: timestamp, value
[ 0 12 3.14 ]: timestamp, elevation, value
[ 0 -45.0 0.2 3.14 ]:timestamp, latitude, longitude, value
[ 0 48.44218 -4.41427 80000 3.14 ]: timestamp, latitude, longitude, elevation, value
```
So timestamp is always at zero index  and value is always the last.
=> Fix Warp10 values when user is using geo metadata

Makefile, docs/installation.rst
* The `make scheduler` command is now working correctly ;
* The scheduler part of the doc is now using absolute paths to add the DepC home into `PYTHONPATH` and the scheduler folder as `AIRFLOW_HOME`.
=> Fix Makefile/Doc for the Scheduler part

Makefile, consumer/kafka_consumer/utils.py, consumer/main.py, depc/__init__.py, docs/installation.rst, scheduler/dags/generate_dags.py
* In Airflow 1.10:
https://github.com/apache/airflow/blob/master/airflow/operators/subdag_operator.py#L36
The forced use of a `SequentialExecutor` for the `SubdagOperator` cause to DepC to do not use the `airflow.cfg` (`generate_dag.py` rely on `SubdagOperator`).
* Now the configuration (e.g.: `depc.dev.yml`) will use the `DEPC_HOME` env var, the consumer, the API context and the documentation is updated accordingly.
=> Fix scheduler after upgrade to Airflow 1.10 and use absolute path for the YAML conf

depc/controllers/checks.py, depc/controllers/rules.py, tests/apiv1/test_checks.py, tests/apiv1/test_rules.py, ui/app/scripts/controllers/team/checks.js
- This is not anymore possible to create 2 checks with the same name inside a team ;
- The rule and check name cannot have a simple or a double quote at the beginning or at the end of their name ;
- fix an issue when you switch the type of check.
=> Fix: more constraints on the rule and check name

ui/app/views/team/checks.html
Add the text under the **Threshold** field in the **Indicator** form:
> Simple threshold or interval : `42`, `3.14`, `-42`, `100:200` or `-0.1:0.1`. See the [dedicated guide](https://ovh.github.io/depc/guides/indicators.html) for more details.
In these both cases:
- when creating a new indicator ;
- when modifying an existing one.
=> Add hint and link to the doc for the threshold field

depc/commands/user.py, manage.py
Add `flask user create <NAME>` command to the CLI.
Help output:
```
flask user create --help
Usage: flask user create [OPTIONS] NAME
Create a new user.
Options:
--admin
--help      Show this message and exit.
```
=> CLI: add a command to create a new user

consumer/kafka_consumer/__init__.py, depc.example.yml, depc/logs/__init__.py, depc/logs/sinks.py
Enable GELF support into logging with the configuration (`gelf: true` in the `LOGGING` section).
Send log entries as JSON format to the standard output.
=> feat(logs): support Graylog format (GELF) for logging

ui/.npmrc, ui/package.json
8aa01d2 - build(ui): set engines.node to >=8.0
The Docker's image used for the UI is based on `node_8.x stretch`.
see: [`ui/Dockerfile`](https://github.com/ovh/depc/blob/4cdbca70a249abdccd0661f21fc253f0cc082bf0/ui/Dockerfile#L8-L13)
ca10dc8 - build(ui): add .npmrc file
Prevent writing `package-lock.json`.
see: https://docs.npmjs.com/misc/config#package-lock
---
Signed-off-by: Antoine Leblanc <antoine.leblanc@corp.ovh.com>
=> build(ui): set engines.node to >=8.0

depc/schemas/v1_config.json, scheduler/dags/generate_dags.py, scheduler/dags/operators/__init__.py, scheduler/dags/operators/before_subdag_operator.py, scheduler/dags/operators/rule_operator.py
Introducing a new property into the user's configuration in order to exclude specific nodes from the label average computing.
Sample:
```
{
"Apache": {
"label": {
"average.exclude": [
"apache1"
]
},
"qos": "rule.Servers"
},
"Filer": {
"qos": "rule.Servers"
},
"Offer": {
"qos": "aggregation.AVERAGE[Website]"
},
"Website": {
"qos": "operation.AND[Filer, Apache]"
}
}
```
New feature:
```
"label": {
"average.exclude": [
"apache1"
]
}
```
This configuration means you can have a QoS for the `apache1` and prevent this node to affect the average of the label `Apache`.
Possible use case: you are using some staging nodes into your infrastructure computed by DepC but this node should not contribute to your overall QoS.
=> Exclude some nodes from the label average

requirements.txt, scheduler/dags/generate_dags.py
Upgrade the Apache Airflow version, fix the `ImportError` with `GetDefaultExecutor()` (replaced by: `get_default_executor()`).
NB: when upgrading from a previous version of Apache Airflow, you may need to add a `default_pool` into the Pool list (admin panel).
=> bump(scheduler): upgrade to apache airflow 1.10.6

depc.example.yml, depc/apiv1/rules.py, depc/context.py, depc/controllers/rules.py, depc/sources/__init__.py, depc/tasks.py, depc/utils/qos.py, scheduler/dags/operators/rule_operator.py
Use the `EXCLUDE_FROM_AUTO_FILL` in the DepC configuration YAML file to specify which resource (team IDs or rule IDs*) you want to exclude from the regular compute method.
Under the hood, this option will prevent the data points to be back-filled and forward-filled into the Pandas dataframe during the QoS computing.
Example:
```
EXCLUDE_FROM_AUTO_FILL:
- 123e4567-e89b-12d3-a456-426655440000
```
\* The UUIDs for the teams and the rules used as primary keys in the DepC relational database.
=> feat: disable the default auto-filling for some specific use cases

depc/apiv1/dependencies.py, ui/app/scripts/services/dependencies.js
Fix issue with some characters (e.g.: `?`,...) in the node name causing a `404` error in the Dependencies tab (node search feature).
API call: `https://localhost:5000/#/teams/Acme/dependencies?day=2020-05-07&label=Test&node=%2Ftest%2Fplop%2Fok%3Ftest%3Dok%23TEST`
=> fix(ui,api): encode/decode node name with special characters

migrations/versions/88c2ab34728c_rename_check_parameters.py
=> fix(migrations): 'checks' table does not yet exist in first upgrade command

requirements.txt
Bump `apache-airflow` to v1.10.10
Required to avoid some conflicts with DepC API:
* Bump `jsonschema` to v3.2.0
* Bump `flask-sqlalchemy`to v2.4.1
=> bump(scheduler): upgrade airflow to v1.10.10

depc/static/grafana_details_dashboard.json, depc/static/grafana_summary_dashboard.json, requirements.txt
* Due to a conflict with some versions of `flask-admin`, `flask-login` and `alembic`, this PR updates DepC requirements to match Airflow/FlaskAppBuilder requirements.
* Update Grafana templates to change the PluginID for the current [Warp10 data source](https://github.com/ovh/ovh-warp10-datasource/blob/master/plugin.json#L2).
=> Fixes: requirements and grafana templates

.travis.yml, Dockerfile, docs/installation.rst
New info block in installation documentation looks like this:
=> feat: support snappy compression in kafka consumer

Dockerfile
**Fix Pull Request #78** 
As a part of an optional requirement, the `pip install python-snappy` step should be added directly in the `Dockerfile`, not in the `requirements.txt`.
=> fix(docker): add python-snappy package installation in dockerfile

scheduler/dags/generate_dags.py
Enable an Airflow admin to change some DepC DAGs parameters (chunks, schedule intervals) into the Airflow Web UI (_Admin > Variables_).
By default, the variables do not exist in the Airflow database, the default existing behaviour is applied.
**Variable: `chunks`**
Value: `{ "amount": 100, "min_count": 100 }`
Configure when you want to enable the chunk feature. Define the number of chunks with the sub-key `amount` and when to apply chunks (number to nodes).
**Variable: `schedules`**
Value: `{ "team_foo": "15 1 * * *", "team_bar": "30 2 * * *" }`
You can run some DepC team DAGs with different schedule intervals using the crontab syntax.
=> Features for Airflow DAGs

depc/utils/qos.py, tests/utils/test_qos.py
- Value returned by `_compute_qos(..)` was wrong, happened in case of `autofill=False` (e.g.: `EXCLUDE_FROM_AUTO_FILL` from the DepC configuration) with only one data point from the time serie.
- Add some test cases.
=> fix: rework case when compute qos handles one datapoint with no autofill feature

scheduler/dags/operators/operation_operator.py
_Reminder_
`check_enable_auto_fill` will get the IDs from the DepC configuration file:
https://github.com/ovh/depc/blob/a56422fcbc0e6f447e2b58b3ca4270e06b2a4cf1/depc.example.yml#L68-L69
=> fix(scheduler): support auto_fill arg in operation operator

requirements.txt, ui/bower.json
- Fix `color-hash` lib version due to a bug in the UI with new version.
- Fix `async-timeout` lib version (inherited from `aiohttp`) to avoid issue into the API.
=> fix(ui,requirements): avoid unwanted bump for color hash and async-timeout
